In [1]:
import numpy as np
import pandas as pd

## MultiIndex Series in Pandas
A MultiIndex (also known as a Hierarchical Index) in pandas allows you to work with data that has multiple levels of indexing. This feature is particularly useful for handling higher-dimensional data in a more natural way

In [3]:
#lets try to create a multiindex series
index_col = [('epl',2022),('epl',2023),('epl',2024),('laliga',2022),('laliga',2023),('laliga',2024)]
series1 = pd.Series([1007,1008,1009,990,995,999],index=index_col)
print(series1)
type(series1)

(epl, 2022)       1007
(epl, 2023)       1008
(epl, 2024)       1009
(laliga, 2022)     990
(laliga, 2023)     995
(laliga, 2024)     999
dtype: int64

pandas.core.series.Series

but there is problem as both league and year are dependent on each other, to solve this we have to use multiindex object

In [5]:
#multiindex from tuples
index_col = [('epl',2022),('epl',2023),('epl',2024),('laliga',2022),('laliga',2023),('laliga',2024)]
multiindex = pd.MultiIndex.from_tuples(index_col)
multiindex

MultiIndex([(   'epl', 2022),
            (   'epl', 2023),
            (   'epl', 2024),
            ('laliga', 2022),
            ('laliga', 2023),
            ('laliga', 2024)],
           )

In [6]:
multiindex.levels

FrozenList([['epl', 'laliga'], [2022, 2023, 2024]])

In [7]:
multiindex.levels[0]

Index(['epl', 'laliga'], dtype='object')

In [8]:
multiindex.levels[1]

Index([2022, 2023, 2024], dtype='int64')

In [10]:
# multiindex from product
pd.MultiIndex.from_product([['epl','laliga'],[2022,2023,2024]])  #2d list

MultiIndex([(   'epl', 2022),
            (   'epl', 2023),
            (   'epl', 2024),
            ('laliga', 2022),
            ('laliga', 2023),
            ('laliga', 2024)],
           )

In [12]:
# creating a series with multiindex object
s = pd.Series([1007,1008,1009,990,995,999],index=multiindex)
s

epl     2022    1007
        2023    1008
        2024    1009
laliga  2022     990
        2023     995
        2024     999
dtype: int64

In [13]:
#fetching items from such series
s['epl']

2022    1007
2023    1008
2024    1009
dtype: int64

In [14]:
s['laliga']

2022    990
2023    995
2024    999
dtype: int64

In [17]:
s[('epl',2023)]

1008

A MultiIndex series in pandas appears to be 2-dimensional due to its hierarchical indexing structure, but it's fundamentally a 1-dimensional data structure.

In [20]:
#unstack
#converts multiindex series into dataframe
temp = s.unstack()         #-----------> inner index is converted into columns
temp

        2022  2023  2024
epl     1007  1008  1009
laliga   990   995   999

In [27]:
# stack
# converts dataframe into a multiindex series
temp.stack()

epl     2022    1007
        2023    1008
        2024    1009
laliga  2022     990
        2023     995
        2024     999
dtype: int64

In [24]:
type(temp.stack())

pandas.core.series.Series

### what is the reason of using multiindex series or object?

using multiindex object we can represent higher dimensional data using lower object representation, this is helpful if we want to represent 3d,4d or higher dimensional data , we can do that using multiindex dataframe.

- Using multiindex object we can represent any dimensional data using series and dataframe

## MultiIndex DataFrame

In [30]:
league_df1 = pd.DataFrame([[300,1000],[301,999],[301,999],[301,999],[301,999],[301,999]],index=multiindex,columns=['no.of.players','no.of.goals'])
league_df1

             no.of.players  no.of.goals
epl    2022            300         1000
       2023            301          999
       2024            301          999
laliga 2022            301          999
       2023            301          999
       2024            301          999

In [32]:
league_df1.loc['epl']

      no.of.players  no.of.goals
2022            300         1000
2023            301          999
2024            301          999

In [33]:
league_df1.loc['laliga']

      no.of.players  no.of.goals
2022            301          999
2023            301          999
2024            301          999

In [35]:
league_df1.loc[('epl',2023)]

no.of.players    301
no.of.goals      999
Name: (epl, 2023), dtype: int64

In [36]:
type(league_df1.loc[('epl',2023)])

pandas.core.series.Series

In [37]:
league_df1.loc[('epl',2023)]['no.of.players']

301

In [40]:
 # multiindex dataframe from column perspective i.e multiple index in columns
league_df2 = pd.DataFrame([
    [301,999,305,1005],
    [301,999,305,1005],
    [301,999,305,1005]],
             index = [2022,2023,2024],
             columns = pd.MultiIndex.from_product([['epl','laliga'],['no.of.players','no.of.goals']])
)
league_df2

               epl                    laliga
     no.of.players no.of.goals no.of.players no.of.goals
2022           301         999           305        1005
2023           301         999           305        1005
2024           301         999           305        1005

In [41]:
#fetching item from this dataframe
league_df2['epl']

      no.of.players  no.of.goals
2022            301          999
2023            301          999
2024            301          999

In [42]:
league_df2['laliga']

      no.of.players  no.of.goals
2022            305         1005
2023            305         1005
2024            305         1005

In [43]:
league_df2['laliga']['no.of.goals']

2022    1005
2023    1005
2024    1005
Name: no.of.goals, dtype: int64

In [45]:
# multiindex on both rows and columns
# Creating the MultiIndex for rows
row_index = pd.MultiIndex.from_product([[2022, 2023, 2024], ['A', 'B', 'C']], names=['Year', 'Type'])

# Creating the DataFrame with MultiIndex for both rows and columns
league_df3 = pd.DataFrame([
    [301, 999, 305, 1005],
    [301, 999, 305, 1005],
    [301, 999, 305, 1005],
    [301, 999, 305, 1005],
    [301, 999, 305, 1005],
    [301, 999, 305, 1005],
    [301, 999, 305, 1005],
    [301, 999, 305, 1005],
    [301, 999, 305, 1005]],
    index=row_index,
    columns=pd.MultiIndex.from_product([['epl', 'laliga'], ['no.of.players', 'no.of.goals']])
)
league_df3

                    epl                    laliga
          no.of.players no.of.goals no.of.players no.of.goals
Year Type
2022 A              301         999           305        1005
     B              301         999           305        1005
     C              301         999           305        1005
2023 A              301         999           305        1005
     B              301         999           305        1005
     C              301         999           305        1005
2024 A              301         999           305        1005
     B              301         999           305        1005
     C              301         999           305        1005

in this dataframe if i want to fetch a particular item i required 4 information(year,type,epl/laliga,no.of.players/no.of.goals) so this data is 4d which is represented as dataframe using multiindex object.

### Stacking and unstacking

In [46]:
#unstacking
#convert inner rows to column
league_df1

             no.of.players  no.of.goals
epl    2022            300         1000
       2023            301          999
       2024            301          999
laliga 2022            301          999
       2023            301          999
       2024            301          999

In [47]:
league_df1.unstack()

       no.of.players           no.of.goals
                2022 2023 2024        2022 2023 2024
epl              300  301  301        1000  999  999
laliga           301  301  301         999  999  999

inner row that is year is now converted to column

In [49]:
league_df1.unstack().unstack()  # now row at level 0 is also converted to column

no.of.players  2022  epl        300
                     laliga     301
               2023  epl        301
                     laliga     301
               2024  epl        301
                     laliga     301
no.of.goals    2022  epl       1000
                     laliga     999
               2023  epl        999
                     laliga     999
               2024  epl        999
                     laliga     999
dtype: int64

In [57]:
league_df3

                    epl                    laliga
          no.of.players no.of.goals no.of.players no.of.goals
Year Type
2022 A              301         999           305        1005
     B              301         999           305        1005
     C              301         999           305        1005
2023 A              301         999           305        1005
     B              301         999           305        1005
     C              301         999           305        1005
2024 A              301         999           305        1005
     B              301         999           305        1005
     C              301         999           305        1005

In [59]:
league_df3.unstack().unstack()  #4d series with 4 index

                       Type  Year
epl     no.of.players  A     2022     301
                             2023     301
                             2024     301
                       B     2022     301
                             2023     301
                             2024     301
                       C     2022     301
                             2023     301
                             2024     301
        no.of.goals    A     2022     999
                             2023     999
                             2024     999
                       B     2022     999
                             2023     999
                             2024     999
                       C     2022     999
                             2023     999
                             2024     999
laliga  no.of.players  A     2022     305
                             2023     305
                             2024     305
                       B     2022     305
                             2023     305
                             2024     305
                       C     2022     305
                             2023     305
                             2024     305
        no.of.goals    A     2022    1005
                             2023    1005
                             2024    1005
                       B     2022    1005
                             2023    1005
                             2024    1005
                       C     2022    1005
                             2023    1005
                             2024    1005
dtype: int64

In [50]:
#stacking
#oppisite of unstacking
# coverts inner columns to rows
league_df2

               epl                    laliga
     no.of.players no.of.goals no.of.players no.of.goals
2022           301         999           305        1005
2023           301         999           305        1005
2024           301         999           305        1005

In [52]:
unstacked_df = league_df2.unstack()
unstacked_df

epl     no.of.players  2022     301
                       2023     301
                       2024     301
        no.of.goals    2022     999
                       2023     999
                       2024     999
laliga  no.of.players  2022     305
                       2023     305
                       2024     305
        no.of.goals    2022    1005
                       2023    1005
                       2024    1005
dtype: int64

In [53]:
unstacked_df.stack()

AttributeError: 'Series' object has no attribute 'stack'

Stack wont work with series

In [54]:
league_df1

             no.of.players  no.of.goals
epl    2022            300         1000
       2023            301          999
       2024            301          999
laliga 2022            301          999
       2023            301          999
       2024            301          999

In [55]:
unstacked_df = league_df1.unstack()
unstacked_df

       no.of.players           no.of.goals
                2022 2023 2024        2022 2023 2024
epl              300  301  301        1000  999  999
laliga           301  301  301         999  999  999

In [56]:
unstacked_df.stack()

C:\Temp\ipykernel_4704\3936091291.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  unstacked_df.stack()

             no.of.players  no.of.goals
epl    2022            300         1000
       2023            301          999
       2024            301          999
laliga 2022            301          999
       2023            301          999
       2024            301          999

year are now converted to rows